site_name: LionIQ 文档
pages: 
- 首页: index.md
- 安装: install.md
- Swift3: swift_3_api.md
- Swift2.3: swift_2.3_api.md
- Obj-C: objc_api.md
- JSON 对象: json_objects.md
- 储存订单信息: order_data_json.md
- 后台管理: dashboard.md
theme: readthedocs